version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: settings/php/lminio.app.dockerfile
    #image: digitalocean.com/php
    container_name: lminio.app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    #- ./settings/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  wserver:
    build:
        context: .
        dockerfile: settings/nginx/lminio.wserver.dockerfile
    #image: nginx:alpine
    container_name: lminio.wserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./settings/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.6
    container_name: lminio.db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./settings/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
# The phpmyadmin
  phpmyadmin:
    depends_on:
            - db
    image: phpmyadmin/phpmyadmin
    container_name: lminio.phpmyadmin
    restart: always
    ports:
            - 8088:80
    environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
    networks:
            - app-network
# The minio
  minio:
    image: geoincaks/lminio.wserver
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: TCI4823FJXBK0206GOXX
      MINIO_SECRET_KEY: xHC90qBeyZW04r+4bWf8gOn2pYGlFhfLzgcotBGn
    command: server /data
    networks:
      - app-network
#Docker Networks
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local